#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd -m 1 & # Start sxhkd after setting the keyboard layout for non QWERTYs

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width	2
bspc config window_gap		0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


### Window rules
# Desktop
bspc rule -a code-oss desktop='^1'
bspc rule -a *:Navigator desktop='^2' # Any web browser
bspc rule -a Gimp desktop='^8' state=floating follow=on

# Special
bspc rule -a Pavucontrol state=floating
bspc rule -a Gpick state=floating
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


### Autostart
# 1080p resolution
xrandr --output Virtual-1 --mode 1920x1080 --rate 144

# Compositor
# picom --no-vsync -b &

# Polybar
sh "$HOME/.config/polybar/launch.sh" &

# Background
feh ~/Downloads/00016-191680279-a-city-skyline-with-birds-a-skyscraper-with-an-red-illuminated-antenna-on-its-top.png --bg-fill

