#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd -m 1 & # Start sxhkd after setting the keyboard layout for non QWERTYs

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width	2
bspc config window_gap		0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color        "#F1CB7E"
# bspc config normal_border_color         "#073642"
# bspc config active_border_color         "#FF0000"


### Window rules
# Desktop
bspc rule -a code-oss desktop='^1'
bspc rule -a *:Navigator desktop='^2' # Any web browser
bspc rule -a social:Navigator desktop='^3' # Social firefox profile
bspc rule -a FreeTube desktop='^3'
bspc rule -a obsidian desktop='^4'
bspc rule -a krita desktop='^5'
bspc rule -a Signal desktop='^6'
bspc rule -a Yad desktop='^8' state=floating follow=on # Stl
bspc rule -a streaming_client desktop='^8' # Steam remoteplay
bspc rule -a overwatch.exe desktop='^8'
bspc rule -a stratz desktop='^9'
bspc rule -a Steam desktop='^9' state=tiled follow=off
bspc rule -a bottles desktop='^9' follow=off


# Special
bspc rule -a Pavucontrol state=floating
bspc rule -a Gpick state=floating
bspc rule -a Signal:signal:"Sharing screen" sticky=on state=floating
bspc rule -a firefox:Toolkit state=floating sticky=on rectangle=210x120
bspc rule -a *:*:"Picture in picture" state=floating sticky=on rectangle=640x360

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


### Autostart
# 1080p resolution
# xrandr --output Virtual-1 --mode 1920x1080 --rate 144

# Numlock
numlockx

# Compositor
picom -b &

# Polybar
sh "$HOME/.config/polybar/launch.sh" &

# Background
feh /mnt/datadrive/Images/Wallpapers/shinjuku-tokyo-mimimal-4k-o8.jpg --bg-fill

# ICC Profile
xcalib /mnt/four/data/download/asus_vg248qe_svet.icm

# Launch CKB and close immediately
ckb-next

